create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  image text not null,
  category text not null
);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);
