import type { CatalogCategoryFilter } from "@/lib/products";
import type { Lang } from "@/lib/i18n";

/** Подписи категорий для фильтра и для карточек уровня 1 */
export const CATEGORY_LABELS: Record<CatalogCategoryFilter, Record<Lang, string>> = {
  Все: { ru: "Все", en: "All", de: "Alle", kk: "Барлығы", uk: "Усі", uz: "Barchasi" },
  "Гофре в горошек": {
    ru: "Гофре в горошек",
    en: "Polka-dot crinkle",
    de: "Crêpe mit Punkten",
    kk: "Бұршақты гофре",
    uk: "Гофре в горошок",
    uz: "Nuqtali gofre",
  },
  "Гофре в фактурный горошек": {
    ru: "Гофре в фактурный горошек",
    en: "Speckled crinkle",
    de: "Crêpe mit Sprenkeln",
    kk: "Дақты гофре",
    uk: "Гофре в фактурний горошок",
    uz: "Nuqtali mayda gofre",
  },
  "Шифон гофре цветок": {
    ru: "Шифон гофре цветок",
    en: "Chiffon floral crinkle",
    de: "Chiffon-Crêpe mit Blumen",
    kk: "Шифон гофре гүлді",
    uk: "Шифон гофре в квіточок",
    uz: "Shifon gulli gofre",
  },
  "Атлас гофре принт": {
    ru: "Атлас гофре принт",
    en: "Atlas gofre print",
    de: "Atlas-Gofre-Print",
    kk: "Атлас гофре принт",
    uk: "Атлас гофре принт",
    uz: "Atlas gofre print",
  },
  "Атлас принт": {
    ru: "Атлас принт",
    en: "Atlas print",
    de: "Atlas-Print",
    kk: "Атлас принт",
    uk: "Атлас принт",
    uz: "Atlas print",
  },
  "Гофре принт": {
    ru: "Гофре принт",
    en: "Crinkle print",
    de: "Crêpe-Druck",
    kk: "Гофре принт",
    uk: "Гофре принт",
    uz: "Gofre print",
  },
  "Зауженный атлас": {
    ru: "Зауженный атлас",
    en: "Tapered atlas",
    de: "Schmaler Atlas",
    kk: "Тарылған атлас",
    uk: "Заужений атлас",
    uz: "Toraytirilgan atlas",
  },
  "Зауженный гофре": {
    ru: "Зауженный гофре",
    en: "Tapered crinkle",
    de: "Schmaler Crêpe",
    kk: "Тарылған гофре",
    uk: "Заужений гофре",
    uz: "Toraytirilgan gofre",
  },
  "Зауженная жатка": {
    ru: "Зауженная жатка",
    en: "Tapered crinkle weave",
    de: "Schmale Crashstruktur",
    kk: "Тарылған жатка",
    uk: "Заужена жатка",
    uz: "Toraytirilgan zhatka",
  },
  "Зауженные с проблеском": {
    ru: "Зауженные с проблеском",
    en: "Tapered shimmer",
    de: "Schmal mit Schimmer",
    kk: "Жарқылы бар тарылған",
    uk: "Заужені з проблиском",
    uz: "Yaltirashli toraytirilgan",
  },
  "Зауженный шифон": {
    ru: "Зауженный шифон",
    en: "Tapered chiffon",
    de: "Schmaler Chiffon",
    kk: "Тарылған шифон",
    uk: "Заужений шифон",
    uz: "Toraytirilgan shifon",
  },
  "Косынка в фактурный горошек": {
    ru: "Косынка в фактурный горошек",
    en: "Speckled kerchief",
    de: "Tuch mit Sprenkeln",
    kk: "Дақты косынка",
    uk: "Косинка в крапинку",
    uz: "Mayda nuqtali ro'molcha",
  },
  "Косынка ромб гофре": {
    ru: "Косынка ромб гофре",
    en: "Diamond crinkle kerchief",
    de: "Rauten-Crêpe-Tuch",
    kk: "Ромб гофре косынка",
    uk: "Косинка ромб гофре",
    uz: "Romb gofre ro'molcha",
  },
  "Шарф в фактурный горошек": {
    ru: "Шарф в фактурный горошек",
    en: "Speckled scarf",
    de: "Schal mit Sprenkeln",
    kk: "Дақты шарф",
    uk: "Шарф в фактурний горошок",
    uz: "Mayda nuqtali sharf",
  },
};
